controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

homepage:
    path: /
    controller: App\Controller\HomeController::index

subscription_change:
    path: /subscription/change
    controller: App\Controller\SubscriptionController::changeSubscription

pdf_generation:
    path: /pdf/convert
    controller: App\Controller\PdfController::generatePdf

history:
    path: /history
    controller: App\Controller\HistoryController::index